-- MySQL Script generated by MySQL Workbench
-- Tue Mar  4 09:15:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema traffic_tracker_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema traffic_tracker_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `traffic_tracker_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `traffic_tracker_db` ;

-- -----------------------------------------------------
-- Table `traffic_tracker_db`.`website`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traffic_tracker_db`.`website` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origin` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `traffic_tracker_db`.`page`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traffic_tracker_db`.`page` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(255) NOT NULL,
  `websiteId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_94e97a381341be377890b578a62` (`websiteId` ASC) VISIBLE,
  CONSTRAINT `FK_94e97a381341be377890b578a62`
    FOREIGN KEY (`websiteId`)
    REFERENCES `traffic_tracker_db`.`website` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `traffic_tracker_db`.`visit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `traffic_tracker_db`.`visit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` TIMESTAMP NOT NULL,
  `pageId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_992dbd13aa7ee7ae506461f183a` (`pageId` ASC) VISIBLE,
  CONSTRAINT `FK_992dbd13aa7ee7ae506461f183a`
    FOREIGN KEY (`pageId`)
    REFERENCES `traffic_tracker_db`.`page` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 49
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
